[project]
name = "uv_openstack"
version = "0.2.0"
description = "A simple environment to run OpenStack SDK and CLI tools with uv"
authors = [{name = "thomaslaurenson", email = "thomas@thomaslaurenson.com"}]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openstacksdk>=4.0.0",
    "python-openstackclient>=10.0.0",
    "nectarallocationclient>=2.0.0",
    "varroaclient>=1.4.0",
    "python-barbicanclient>=7.0.0",
    "pysocks>=1.7.1",
]
